import { existsSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import type { I18nKitConfig, LocaleConfig } from './schema.js'

export type { I18nKitConfig, LocaleConfig, LocaleMeta } from './schema.js'

export const CONFIG_FILENAME = 'i18n-kit.config.json'

export function findConfigPath(cwd: string): string | null {
  const p = join(cwd, CONFIG_FILENAME)
  return existsSync(p) ? p : null
}

export function readConfig(cwd: string): I18nKitConfig | null {
  const p = findConfigPath(cwd)
  if (!p) return null
  try {
    return JSON.parse(readFileSync(p, 'utf-8')) as I18nKitConfig
  } catch {
    return null
  }
}

export function writeConfig(cwd: string, config: I18nKitConfig): void {
  const p = join(cwd, CONFIG_FILENAME)
  writeFileSync(p, JSON.stringify(config, null, 2) + '\n', 'utf-8')
}

/** Creates a `.backup` copy before overwriting an existing file. */
export function backupFile(filePath: string): void {
  if (existsSync(filePath)) {
    copyFileSync(filePath, filePath + '.backup')
  }
}

/**
 * Resolves the base locale directory from the `extends` field.
 * Returns null if extends is not set or can't be resolved.
 */
export function resolveExtendsDir(cwd: string, config: I18nKitConfig): string | null {
  if (!config.extends) return null
  const target = resolve(cwd, config.extends)
  if (!existsSync(target)) return null

  // If target is a config file, use its directory
  try {
    const stat = existsSync(target) && readFileSync(target, 'utf-8')
    if (stat && target.endsWith('.json')) {
      const baseConfig = JSON.parse(stat as string) as I18nKitConfig
      if (baseConfig.localesDir) {
        return resolve(dirname(target), baseConfig.localesDir)
      }
      return dirname(target)
    }
  } catch { /* fall through */ }

  return target
}

/**
 * Reads base locale data from the extends directory.
 * Returns a map of code → flat key/value record.
 */
export function readBaseLocales(
  baseDir: string,
): Record<string, Record<string, unknown>> {
  const result: Record<string, Record<string, unknown>> = {}
  try {
    const { readdirSync } = require('node:fs') as typeof import('node:fs')
    const files = readdirSync(baseDir).filter((f: string) => f.endsWith('.json'))
    for (const file of files) {
      const code = file.slice(0, -5)
      try {
        result[code] = JSON.parse(readFileSync(join(baseDir, file), 'utf-8')) as Record<string, unknown>
      } catch { /* skip malformed */ }
    }
  } catch { /* dir not readable */ }
  return result
}

/**
 * Derives the normalized locales list used by the UI server and
 * `i18n-tools/locales.config.json`. Resolves relative paths to absolute.
 */
export function deriveLocalesMap(
  cwd: string,
  config: I18nKitConfig,
): Array<{ code: string; path: string; meta?: Record<string, unknown> }> {
  return config.locales.map(l => ({
    code: l.code,
    path: resolve(cwd, l.path),
    ...(l.meta ? { meta: l.meta as Record<string, unknown> } : {}),
  }))
}

/**
 * Generates the legacy `locales.config.json` content that the UI server
 * reads when there is no `i18n-kit.config.json`.
 */
export function buildLegacyLocalesConfig(
  cwd: string,
  config: I18nKitConfig,
): { root: string; generatedAt: string; locales: ReturnType<typeof deriveLocalesMap> } {
  return {
    root: cwd,
    generatedAt: new Date().toISOString(),
    locales: deriveLocalesMap(cwd, config),
  }
}

/**
 * Reads locale config for the UI server.
 * Tries `i18n-kit.config.json` first, then falls back to the legacy
 * `i18n-tools/locales.config.json` generated by `auto-config`.
 */
export function readLocalesForServer(cwd: string): {
  locales: Array<{ code: string; path: string; meta?: Record<string, unknown> }>
  source: 'kit-config' | 'legacy'
  baseLocalesDir?: string
} | null {
  const config = readConfig(cwd)
  if (config?.locales.length) {
    const baseLocalesDir = resolveExtendsDir(cwd, config) ?? undefined
    return { locales: deriveLocalesMap(cwd, config), source: 'kit-config', baseLocalesDir }
  }

  const legacyPath = join(cwd, 'i18n-tools', 'locales.config.json')
  if (existsSync(legacyPath)) {
    try {
      const legacy = JSON.parse(readFileSync(legacyPath, 'utf-8'))
      if (Array.isArray(legacy.locales) && legacy.locales.length) {
        return { locales: legacy.locales as Array<{ code: string; path: string; meta?: Record<string, unknown> }>, source: 'legacy' }
      }
    } catch {
      // fall through
    }
  }

  return null
}
