import { readFileSync, writeFileSync, existsSync, readdirSync, watchFile, unwatchFile } from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import { readConfig } from '../../config/index.js'

export interface TypesOptions {
  /** Output path for the generated .d.ts file */
  out?: string
  /** Locale code to use as key source (default: first in config) */
  locale?: string
  /** Locales directory (used when no config found) */
  dir?: string
  /** Watch locale files for changes and regenerate */
  watch?: boolean
}

function flattenKeys(obj: Record<string, unknown>, prefix = ''): string[] {
  const keys: string[] = []
  for (const [k, v] of Object.entries(obj)) {
    const full = prefix ? `${prefix}.${k}` : k
    if (v !== null && typeof v === 'object' && !Array.isArray(v)) {
      keys.push(...flattenKeys(v as Record<string, unknown>, full))
    } else {
      keys.push(full)
    }
  }
  return keys
}

function generateDts(keys: string[]): string {
  const sorted = [...new Set(keys)].sort()
  const union = sorted.map(k => `  | ${JSON.stringify(k)}`).join('\n')
  return [
    '// This file is auto-generated by vue-i18n-kit. Do not edit manually.',
    '// Run: npx vue-i18n-kit types',
    '',
    `export type TranslationKey =`,
    union + ';',
    '',
    `export type TranslationKeyPrefix = {`,
    `  [K in TranslationKey]: K extends \`\${infer Prefix}.\${string}\` ? Prefix : never`,
    `}[TranslationKey];`,
    '',
    `declare module 'vue-i18n-kit' {`,
    `  interface Register {`,
    `    key: TranslationKey`,
    `  }`,
    `}`,
    '',
  ].join('\n')
}

function resolveLocaleFile(cwd: string, options: TypesOptions): string | null {
  const config = readConfig(cwd)

  if (config?.locales.length) {
    const target = options.locale
      ? config.locales.find(l => l.code === options.locale)
      : config.locales[0]
    if (target) return resolve(cwd, target.path)
  }

  // Fallback: scan directory
  const dir = resolve(cwd, options.dir ?? 'src/locales')
  if (!existsSync(dir)) return null

  const files = readdirSync(dir).filter(f => f.endsWith('.json')).sort()
  if (!files.length) return null

  if (options.locale) {
    const match = files.find(f => f === `${options.locale}.json`)
    return match ? join(dir, match) : null
  }
  return join(dir, files[0])
}

function generate(localeFile: string, outPath: string): void {
  let data: Record<string, unknown>
  try {
    data = JSON.parse(readFileSync(localeFile, 'utf-8')) as Record<string, unknown>
  } catch {
    console.error(`✗ Failed to parse: ${localeFile}`)
    process.exit(1)
  }

  const keys = flattenKeys(data)
  const dts = generateDts(keys)
  writeFileSync(outPath, dts, 'utf-8')
}

export function runTypes(options: TypesOptions): void {
  const cwd = process.cwd()
  const outPath = resolve(cwd, options.out ?? 'src/i18n.d.ts')

  const localeFile = resolveLocaleFile(cwd, options)
  if (!localeFile) {
    console.error('✗ No locale file found. Use --dir or run vue-i18n-kit init first.')
    process.exit(1)
  }

  generate(localeFile, outPath)
  const relOut = outPath.replace(cwd, '').replace(/\\/g, '/').replace(/^\//, '')
  const relSrc = localeFile.replace(cwd, '').replace(/\\/g, '/').replace(/^\//, '')
  console.log(`✓ Generated ${relOut} from ${relSrc} (${flattenKeys(JSON.parse(readFileSync(localeFile, 'utf-8')) as Record<string, unknown>).length} keys)`)

  if (options.watch) {
    console.log(`  Watching ${relSrc} for changes…`)
    watchFile(localeFile, { interval: 500 }, () => {
      try {
        generate(localeFile, outPath)
        console.log(`  ↺  Regenerated ${relOut}`)
      } catch { /* ignore parse errors during watch */ }
    })
    process.on('SIGINT', () => { unwatchFile(localeFile); process.exit(0) })
    process.on('SIGTERM', () => { unwatchFile(localeFile); process.exit(0) })
  }
}
