/**
 * Entry point for the dev-overlay browser bundle.
 * Compiled by `vite build --config vite.config.dev-overlay.mts` into
 * `dist/vite-plugin/dev-overlay/index.js` and imported at runtime by the
 * virtual module generated by `vueI18nDevPlugin`.
 */
export { default as I18nInspect } from './I18nInspect.vue'
export { default as DevOverlay } from './DevOverlay.vue'
export { emitEdit, onEdit } from './eventBus'
export type { I18nEditPayload } from './eventBus'
export { vI18nInspect } from './directive'
